name: Unikorn Push
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
env:
  GO_VERSION: 1.22.1
jobs:
  Static:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: License Checker
      run: make license
  Runtime:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Golang CI/Helm Lint
      run: make lint
